### ISSUE TITLE
typescript v3.0.16 dependency causes issue with react-typescript compiler v3.0.19

### ISSUE THREAD

**Issue by fabgallo** [teambit/bit.envs#54] opened 2019-09-04 10:42 UTC
![image](https://user-images.githubusercontent.com/2903427/64247812-a2723a00-cedd-11e9-8279-ce2fac20f85d.png)

The compiler is the only thing I changed in my project (`bit import bit.envs/compilers/react-typescript -c`).
If I change the version back to 3.0.17 and lower in `bit.json`, it works.

**Comment by GiladShoham** [comment] 2019-09-04 12:16
Quick update:
we found the root cause for this. we are working to resolve it and will publish a new version soon.

**Comment by qballer** [comment] 2019-09-04 13:15
`bit import bit.envs/compilers/react-typescript@3.0.21 -c` should resolve this issue. We found the root cause of the issue. The compiler failed to find the main dist file so bit directed the code to the source. I"m closing this issue, let me know if it is working. Seems so on my side.

**Closed by qballer** 2019-09-04 13:15 UTC
